# Site settings
title: Kernel32.net
description: > # this means to ignore newlines until "baseurl:"
  Oddbjørn U. Bakke
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kernel32.net" # the base hostname & protocol for your site
enforce_ssl: kernel32.net
twitter_username: oddbeard
github_username:  oddbear
#linkedin:         oddbjornbakke

# Build settings
markdown: kramdown
